# Supplementary Table 1: Descriptive Statistics

# libraries

In [1]:
import pandas as pd
import numpy as np

# parameter

In [2]:
input_path = ''
ouput_path = ''

# data

In [3]:
data = pd.read_csv(input_path)
columns = list(data)[1:-1]

# descriptive statistics

In [4]:
overall_mean = []
overall_std = []
vse_mean = []
vse_std = []
control_mean = []
control_std = []

for col in columns: 
    overall_mean.extend([data[col].mean()])
    overall_std.extend([data[col].std()])
    vse_mean.extend([data.loc[data.exclusion==1,col].mean()])
    vse_std.extend([data.loc[data.exclusion==1,col].std()])
    control_mean.extend([data.loc[data.exclusion==0,col].mean()])
    control_std.extend([data.loc[data.exclusion==0,col].std()])  
    
df_desc_stats = pd.DataFrame(data = list(zip(overall_mean,
                                             overall_std,
                                             vse_mean,
                                             vse_std,
                                             control_mean,
                                             control_std)),
                             index = columns,
                             columns = ['overall_mean', 
                                        'overall_std',
                                        'vse_mean', 
                                        'vse_std',
                                        'control_mean', 
                                        'control_std'])

In [5]:
df_desc_stats.round(1)

,overall_mean,overall_std,vse_mean,vse_std,control_mean,control_std
total_number_of_sessions,101.7,170.0,90.1,132.5,103.1,174.0
total_bets,29193.7,129199.1,30540.7,56499.6,29027.9,135476.8
bets_per_session,224.5,253.6,326.3,302.3,211.9,244.0
var_bets_per_session,126907.9,4039190.3,177205.2,459343.1,120717.6,4277479.3
distinct_games_per_session,3.0,2.4,3.4,2.5,2.9,2.3
var_distinct_games_per_session,9.5,28.6,12.2,27.6,9.1,28.7
total_money_bet,67103.3,270165.6,85305.3,206068.3,64863.1,276953.4
money_bet_per_session,697.6,2315.9,1346.4,3516.1,617.8,2108.2
var_money_bet_per_session,12782508.1,201573524.2,30631357.4,363815474.6,10585773.7,171187543.8
days_gambled,57.5,71.8,47.9,55.7,58.6,73.5
sessions_per_day,1.2,0.5,1.3,0.6,1.2,0.5
avg_session_length_in_seconds,2202.9,1782.6,3010.7,2121.1,2103.5,1710.3
var_session_length_in_seconds,7598110.4,15263830.9,12354395.6,18161581.5,7012733.9,14763293.1
total_promo_amt,71.6,268.0,78.7,226.3,70.7,272.6
promo_amt_per_session,0.8,2.4,0.8,2.6,0.7,2.4
total_net_losses,2939.3,9019.5,3926.1,8939.2,2817.9,9022.1
net_losses_per_session,37.7,109.7,72.2,170.2,33.5,99.0
bets_per_day,345.4,490.4,539.2,496.7,321.6,484.3
total_net_wins,237.9,6414.1,279.7,4681.3,232.8,6596.0
net_wins_per_session,3.4,68.1,5.4,52.6,3.1,69.8